//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.HP.pipelinemaker.model;

import java.util.UUID;

import com.hp.api.Id;
import com.hp.sdn.Model;

/**
 * Sample PipelineMaker domain model.
 */
public class PipelineMaker extends Model<PipelineMaker> {

    private static final long serialVersionUID = 7571309040451072286L;

    // Just to make the sample a bit more interesting.
    private String name;

    /** 
     * Default constructor required for serialization.
     */
    public PipelineMaker() {
        super();
    }

    /** 
     * Creates a new PipelineMaker entity. 
     *
     * @param name PipelineMaker name
     */
    public PipelineMaker(String name) {
        super();
        this.name = name;
    }

    /** 
     * Creates a new PipelineMaker entity. 
     *
     * @param id PipelineMaker unique id
     * @param name PipelineMaker name
     */
    public PipelineMaker(Id<PipelineMaker, UUID> id, String name) {
        super(id);
        this.name = name;
    }
    
    /**
     * Get the PipelineMaker name.
     *
     * @return PipelineMaker name
     */
    public String name() {
        return name;
    }

    /**
     * Set the PipelineMaker name.
     *
     * @param name new name
     */
    public void setName(String name) {
        this.name = name;
    }
}
