//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.HP.pipelinemaker.model;

/**
 * PipelineMaker sort attribute.
 */
public enum PipelineMakerSortAttribute {

    /** Sorts by name */
    NAME

}
