//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.HP.pipelinemaker.model;

import static org.junit.Assert.*;

import org.junit.Test;

import java.util.UUID;

import com.hp.api.Id;

/**
 * Sample test of the PipelineMaker domain model.
 */
public class PipelineMakerTest {

    @Test
    public void basic() {
        Id<PipelineMaker, UUID> id = Id.valueOf(UUID.randomUUID());
        PipelineMaker s = new PipelineMaker(id, "Gizmo");
        assertEquals("incorrect id", id, s.getId());
        assertEquals("incorrect name", "Gizmo", s.name());
    }

}
