//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.HP.pipelinemaker.rs;

import static org.easymock.EasyMock.createMock;
import static org.easymock.EasyMock.expect;
import static org.easymock.EasyMock.replay;
import static org.easymock.EasyMock.verify;

import java.util.UUID;

import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;

import javax.ws.rs.core.MediaType;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.hp.util.rs.ResourceTest;
import com.hp.sdn.rs.misc.ControllerResourceTest;

import com.HP.pipelinemaker.model.PipelineMaker;
import com.HP.pipelinemaker.api.PipelineMakerService;

import com.hp.api.Id;


/**
 * Sample PipelineMaker REST API resource.
 */
public class PipelineMakerResourceTest extends ControllerResourceTest {

    private PipelineMakerService svc;
    
    /**
     * Creates a test suite on the default package set.
     */
    public PipelineMakerResourceTest() {
        super("com.HP.pipelinemaker.rs");
    }
    

    @Override
    @Before
    public void setUp() throws Exception {
        super.setUp();
        svc = createMock(PipelineMakerService.class);

        sl.register(PipelineMakerService.class, svc,
                    Collections.<String, Object> emptyMap());

        // If a specific test case expects a different format, such
        // format will have to be set calling this method.
        ResourceTest.setDefaultMediaType(MediaType.APPLICATION_JSON);
    }
    
    @Override
    @After
    public void tearDown() throws Exception {
        super.tearDown();
        sl.unregister(PipelineMakerService.class, svc);
    }   

    @Test
    public void addPipelineMaker() {
        PipelineMaker s = new PipelineMaker("Thingie");
        
        expect(svc.create("Thingie"))
            .andReturn(s);
        replay(svc);
        
        String r = post("pipelinemaker",  
                        "{\"item\":{\"name\":\"Thingie\"}}");
        assertResponseContains(r, "\"uid\":\"" + s.getId().getValue() + "\"", "\"name\":\"Thingie\"");
        verify(svc);
    }

    @Test
    public void getPipelineMaker() {
        Id<PipelineMaker, UUID> id = Id.valueOf(UUID.randomUUID());
        
        expect(svc.get(id)).andReturn(new PipelineMaker(id, "Thingie"));
        replay(svc);
        
        String r = get("pipelinemaker/" + id.getValue());
        assertResponseContains(r, "\"uid\":\"" + id.getValue() + "\"", "\"name\":\"Thingie\"");
        verify(svc);
    }

    @Test
    public void getAll() {
        Id<PipelineMaker, UUID> id1 = Id.valueOf(UUID.randomUUID());
        Id<PipelineMaker, UUID> id2 = Id.valueOf(UUID.randomUUID());

        Collection<PipelineMaker> c = new HashSet<PipelineMaker>();
        c.add(new PipelineMaker(id1, "Thingie"));
        c.add(new PipelineMaker(id2, "Doo-Hickey"));
        expect(svc.getAll()).andReturn(c);
        replay(svc);

        String r = get("pipelinemaker");
        assertResponseContains(r, "\"pipelinemaker\":[",
                               "{\"uid\":\"" + id1.getValue() + "\"", "{\"uid\":\"" + id2.getValue() + "\"");
        verify(svc);
    }

    @Test
    public void deletePipelineMaker() {
        Id<PipelineMaker, UUID> id = Id.valueOf(UUID.randomUUID());
        
        svc.delete(id);
        replay(svc);
        
        String r = delete("pipelinemaker/" + id.getValue());
        verify(svc);
    }
}
